on: [push]
...
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: yesolutions/mirror-action@master
          with:
            REMOTE: 'https://codeberg.org/Freakybob/Freakybob.site'
            GIT_USERNAME: wish13yt
            GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
            DEBUG: "true"
